name: Publish Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: |
        yarn

    - name: Lint
      run: |
        yarn lint

    - name: Build
      run: |
        yarn build

    - name: Test
      run: |
        yarn test

    - name: Publish
      run: |
        npm publish
